package com.shayan.remindersios.data.models

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

/**
 * Represents a task entity stored in the Room database.
 *
 * @property roomTaskId The unique identifier for the task, autogenerated by Room.
 * @property title The title of the task (required).
 * @property notes Additional notes or description for the task (optional).
 * @property date The scheduled date for the task in the format "yyyy-MM-dd" (optional).
 * @property dateCompleted The date when the task was completed, in the format "yyyy-MM-dd" (optional).
 * @property time The specific time for the task in the format "HH:mm" (optional).
 * @property timeCategory A user-defined category for the time (e.g., "morning", "afternoon", "tonight") (optional).
 * @property timestamp The creation or update timestamp of the task (defaults to the current system time).
 * @property flag Indicates if the task is flagged as important.
 * @property isCompleted Indicates whether the task has been completed.
 */

@Parcelize
@Entity(tableName = "tasks")
data class Tasks(
    @PrimaryKey(autoGenerate = true) val roomTaskId: Int = 0,

    val title: String = "",

    val notes: String? = null,

    val date: String? = null,

    val dateCompleted: String? = null,

    val time: String? = null,

    val timeCategory: String? = null,

    val timestamp: Long = System.currentTimeMillis(),

    val flag: Boolean = false,

    val isCompleted: Boolean = false
) : Parcelable
