package com.shayan.remindersios.data.models

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

/**
 * Represents a task entity stored in the Room database.
 */
@Parcelize
@Entity(tableName = "tasks")
data class Tasks(

    // region Primary Key
    /**
     * The unique identifier for the task, autogenerated by Room.
     */
    @PrimaryKey(autoGenerate = true) val roomTaskId: Int = 0,
    // endregion

    // region Main Fields
    /**
     * The title of the task (required).
     */
    val title: String = "",

    /**
     * Additional notes or description for the task (optional).
     */
    val notes: String? = null,

    /**
     * The scheduled date for the task in the format "yyyy-MM-dd" (optional).
     */
    val date: String? = null,

    /**
     * The date when the task was completed, in the format "yyyy-MM-dd" (optional).
     */
    val dateCompleted: String? = null,

    /**
     * The specific time for the task in the format "HH:mm" (optional).
     */
    val time: String? = null,

    /**
     * A user-defined category for the time (e.g., "morning", "afternoon", "tonight") (optional).
     */
    val timeCategory: String? = null,
    // endregion

    // region Additional Info
    /**
     * The creation or update timestamp of the task (defaults to current system time).
     */
    val timestamp: Long = System.currentTimeMillis(),

    /**
     * Indicates if the task is flagged as important (default false).
     */
    val flag: Boolean = false,

    /**
     * Indicates whether the task has been completed (default false).
     */
    val isCompleted: Boolean = false
    // endregion

) : Parcelable